Repository wkentaro/labelme, pull requests merged in 2018-03, with the labels that each got.

#76 Select label from QListWidget
  labelme/app.py
  labelme/labelDialog.py
Labels: feature

#85 Check self.dirty before switching to double clicked file
  labelme/app.py
Labels: enhancement

#86 Show currently loaded file
  labelme/app.py
Labels: enhancement

#93 Open file from list with a single click
  labelme/app.py
Labels: enhancement

#94 Add completion for label editing
  labelme/labelDialog.py
Labels: enhancement

#96 UI adjustments (select label by arrow key, save/discard/cancel dialog, arrow labels.txt)
  labelme/app.py
  labelme/labelDialog.py
Labels: enhancement

#97 Show errorMessage with not existing file to load
  labelme/app.py
Labels: enhancement

#98 Append to unique label list after edit
  labelme/app.py
Labels: enhancement

#99 Fix imagePath which should be relative to labelfile
  labelme/labelFile.py
Labels: bug

#100 Overwrite existing label file with importDir
  labelme/app.py
  labelme/labelFile.py
Labels: enhancement

#102 Merge semantic_segmentation contrib
  examples/semantic_segmentation/labelme2voc.py
  labelme/utils.py
Labels: enhancement

#103 Fix for flake8 and add flake8 test
  .travis.yml
  examples/instance_segmentation/labelme2voc.py
  examples/semantic_segmentation/labelme2voc.py
  labelme/__init__.py
  labelme/app.py
  labelme/canvas.py
  labelme/cli/__init__.py
  labelme/cli/json_to_dataset.py
  labelme/cli/on_docker.py
  labelme/colorDialog.py
  labelme/labelDialog.py
  labelme/labelFile.py
  labelme/lib.py
  labelme/shape.py
  labelme/toolBar.py
  labelme/zoomWidget.py
  setup.cfg
Labels: enhancement
