Repository wkentaro/labelme, pull requests merged in 2019-01, with the labels that each got.

#286 Fix #266, #285. 'keep_prev' mode is visible in Edit menu and switchable
  labelme/app.py
  labelme/config/default_config.yaml
Labels: feature

#305 Read Exif from image to rotate image correctly
  labelme/app.py
Labels: enhancement

#308 Check if Exif orientation is available
  labelme/app.py
Labels: bug
