Repository wkentaro/labelme, pull requests merged in 2019-08, with the labels that each got.

#466 Fix "No module named 'numpy.random.common'" in pyinstaller
  .travis.yml
Labels: bug

#467 Fix outOfPixmap to solve crashing when outside of the pixmap
  labelme/widgets/canvas.py
Labels: bug

#457 Update README.md
  README.md
Labels: enhancement

#468 Add shortcut for addPointToEdge
  labelme/app.py
  labelme/config/default_config.yaml
Labels: feature

#474 Clip x, y values before calling intersectingEdges
  labelme/widgets/canvas.py
Labels: bug
