Repository wkentaro/labelme, pull requests merged in 2020-07, with the labels that each got.

#707 fix slider_contrast repeated with brightness
  labelme/app.py
Labels: bug

#710 Update labelme.spec
  labelme.spec
Labels: enhancement

#720 Add data_dataset_coco/Visualization
  examples/instance_segmentation/data_dataset_coco/Visualization/2011_000003.jpg
  examples/instance_segmentation/data_dataset_coco/Visualization/2011_000006.jpg
  examples/instance_segmentation/data_dataset_coco/Visualization/2011_000025.jpg
  examples/instance_segmentation/labelme2coco.py
Labels: enhancement

#722 Add sys.setrecursionlimit for Windows
  labelme.spec
Labels: enhancement, windows

#723 Use colorama on Windows
  labelme/logger.py
  setup.py
Labels: enhancement

#719 Easy add/remove point from polygon using SHIFT modifier
  labelme/widgets/canvas.py
Labels: feature

#731 Add black to ci.yml
  .github/workflows/ci.yml
Labels: enhancement
