Repository wkentaro/labelme, pull requests merged in 2020-06, with the labels that each got.

#682 Define encoding: utf-8 for Python2
  labelme/widgets/unique_label_qlist_widget.py
Labels: bug

#494 Added a tool to adjust image brightness and contrast. Useful for dark images
  labelme/app.py
  labelme/widgets/__init__.py
  labelme/widgets/brightness_contrast_dialog.py
  labelme/widgets/canvas.py
Labels: feature

#688 Can't use black to support Python2.7 + virtualenv
  .github/workflows/ci.yml
  pyproject.toml
  setup.py
Labels: bug

#683 Use utf-8 for json encoding
  labelme/label_file.py
Labels: enhancement

#695 Config for shape colors (line_color, fill_color, etc)
  labelme/app.py
  labelme/config/default_config.yaml
  labelme/shape.py
  labelme/widgets/canvas.py
Labels: enhancement

#696 Fix item drag-drop in polygon list
  labelme/widgets/label_list_widget.py
Labels: bug

#697 Call QImageReader.supportedImageFormats later
  labelme/app.py
Labels: bug

#703 Set transparent shape fill_color while drawing
  labelme/config/default_config.yaml
Labels: enhancement
