Repository wkentaro/labelme, pull requests merged in 2020-02, with the labels that each got.

#577 Fix keep_prev and setDirty
  labelme/app.py
Labels: bug

#578 Add windows to CI
  .github/workflows/main.yml
Labels: enhancement

#580 Fix bug caused by unHighlight
  labelme/widgets/canvas.py
Labels: bug

#581 Replace QGuiApplication -> Qt
  labelme/app.py
Labels: bug, windows

#582 Fix saveFileDialog for Windows + PyQt5
  labelme/app.py
Labels: bug, windows

#566 Merge image flags from config and label file
  labelme/app.py
Labels: enhancement

#585 Fix next prev image with QtGui -> Qt
  labelme/app.py
Labels: bug

#589 Use imgviz.asgray
  labelme/cli/json_to_dataset.py
  setup.py
Labels: enhancement

#590 Run pyinstaller in Windows as well
  .github/workflows/main.yml
Labels: enhancement

#565 Preserve other keys on shape level
  labelme/app.py
  labelme/label_file.py
  labelme/shape.py
  tests/labelme_tests/test_app.py
Labels: enhancement

#595 Clear shape highlight correctly
  labelme/widgets/canvas.py
Labels: bug

#596 Fix both unHighlight and addPointToEdge with self.prevXXX
  labelme/widgets/canvas.py
Labels: bug

#598 Press outside of the list to clear selection
  labelme/widgets/unique_label_qlist_widget.py
Labels: enhancement

#597 Replace LabelQListWidget with custom LabelListWidget
  labelme/app.py
  labelme/widgets/__init__.py
  labelme/widgets/label_list_widget.py
  labelme/widgets/label_qlist_widget.py
  tests/labelme_tests/widgets_tests/test_label_list_widget.py
Labels: bug

#600 Fix delete item
  labelme/app.py
  labelme/widgets/label_list_widget.py
Labels: bug
