Repository wkentaro/labelme, pull requests merged in 2020-01, with the labels that each got.

#547 Store zoom value for each filename
  labelme/app.py
Labels: enhancement

#549 Store scroll value
  labelme/app.py
Labels: enhancement

#550 Save self.zoomMode as well
  labelme/app.py
Labels: bug

#553 Add keep_prev_scale
  labelme/app.py
  labelme/config/default_config.yaml
Labels: enhancement

#555 Fix the use of --config arg in main.py
  labelme/config/__init__.py
  labelme/main.py
Labels: bug

#557 Fixed a bug when application crashes on polygon deletion
  labelme/widgets/canvas.py
Labels: bug

#559 Scroll the list of labels to selected item for simpler navigation
  labelme/app.py
Labels: enhancement

#561 Move __version__ to __init__.py
  labelme/__init__.py
  labelme/_version.py
  labelme/label_file.py
  setup.py
Labels: enhancement

#562 Fix fill_drawing initial state
  labelme/app.py
Labels: bug

#567 Clear highlight when leaving from canvas
  labelme/widgets/canvas.py
Labels: enhancement

#568 Deselect shape by labelList
  labelme/app.py
Labels: enhancement

#569 Simplify self.labelItemChanged in app.py
  labelme/app.py
Labels: enhancement

#570 Support ESC in LabelQListWidget
  labelme/widgets/escapable_qlist_widget.py
  labelme/widgets/label_qlist_widget.py
Labels: enhancement

#571 Fix 'version' key load and save in json
  labelme/label_file.py
Labels: bug

#572 Reset self.hShape in Canvas
  labelme/widgets/canvas.py
Labels: bug

#573 Add shape_color, label_colors config
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/shape.py
Labels: feature
