Repository wkentaro/labelme, pull requests merged in 2020-03, with the labels that each got.

#605 fix issue with grayscale images in draw_json
  labelme/cli/draw_json.py
Labels: enhancement

#625 Update readme for Windows install
  README.md
Labels: enhancement, windows

#626 Fixed edit error
  labelme/app.py
Labels: bug
