Repository wkentaro/labelme, pull requests merged in 2021-11, with the labels that each got.

#943 Fixed #933
  labelme/app.py
Labels: bug

#944 Deselect shape when clicking and already selected
  labelme/app.py
  labelme/widgets/canvas.py
Labels: minor-fix/enhancement

#942 Movement with arrow keys
  labelme/app.py
  labelme/widgets/canvas.py
Labels: feature

#945 adaptively approximate the circle shape
  examples/instance_segmentation/labelme2coco.py
Labels: minor-fix/enhancement

#948 Preview images on file dialogs
  labelme/app.py
  labelme/widgets/__init__.py
  labelme/widgets/file_dialog_preview.py
Labels: feature
