Repository wkentaro/labelme, pull requests merged in 2023-12, with the labels that each got.

#1380 Use lxml<5.0.0 for bbox_detection/labelme2voc.py
  .github/workflows/ci.yml
Labels: other

#1379 Use tight bounding box to represent bbox for shape_type="mask"
  labelme/widgets/canvas.py
  setup.py
Labels: enhancement

#1362 os.path.normpath filenames to display paths correctly on Windows
  labelme/app.py
Labels: os: windows, fix

#1384 Regex filename search
  labelme/app.py
Labels: feature
