Repository wkentaro/labelme, pull requests merged in 2024-01, with the labels that each got.

#1391 Handle empty contour case
  labelme/ai/_utils.py
Labels: fix

#1390 Stop using emoji that can cause encoding issue on Windows
  README.md
  setup.py
Labels: fix

#1392 Add copy and paste to edit menu (need to enable shortcut)
  labelme/app.py
Labels: fix

#1370 Use with statement to open file to make code more Pythonic
  tests/labelme_tests/utils_tests/util.py
Labels: enhancement

#1401 Keep selected state when duplicating shapes
  labelme/app.py
Labels: enhancement

#1403 fix a typo
  labelme/shape.py
Labels: other
