Repository wkentaro/labelme, pull requests merged in 2024-06, with the labels that each got.

#1451 Upgrade setup-miniconda
  .github/workflows/ci.yml
Labels: other

#1407 fix a typo
  labelme/app.py
Labels: other

#1452 Save mask as uint8 for better compatibility with other tools
  labelme/app.py
  labelme/label_file.py
Labels: enhancement

#1411 Synced i18n Translation Template and Improved Simplified Chinese Translation
  labelme/app.py
  labelme/translate/empty.ts
  labelme/translate/zh_CN.qm
  labelme/translate/zh_CN.ts
Labels: enhancement

#1429 Update canvas.py
  labelme/widgets/canvas.py
Labels: enhancement

#1455 Support multiple edit of annotations
  labelme/app.py
Labels: feature

#1456 Show xy coordinate in the status bar
  labelme/app.py
  labelme/widgets/canvas.py
Labels: feature
