Repository wkentaro/labelme, pull requests merged in 2025-09, with the labels that each got.

#1630 ci: fix indentation in ci.yml
  .github/workflows/ci.yml
Labels: pr::chore

#1633 chore: upgrade ruff from 0.1.9 to 0.12.11; autofix
  examples/bbox_detection/labelme2voc.py
  labelme/_label_file.py
  labelme/app.py
  labelme/utils/shape.py
  pyproject.toml
  uv.lock
Labels: pr::chore

#1636 ci: check translation files are up-to-date
  .github/workflows/ci.yml
  labelme/translate/empty.ts
  labelme/translate/zh_CN.qm
  labelme/translate/zh_CN.ts
Labels: pr::test

#1637 ci: use cache-apt-pkgs-action to speed up CI
  .github/workflows/ci.yml
Labels: pr::test

#1651 fix: prevent overwriting items when dragging and dropping in label list
  labelme/widgets/label_list_widget.py
Labels: pr::fix

#1655 Fix brightness/contrast for PNG image
  labelme/app.py
  labelme/widgets/brightness_contrast_dialog.py
Labels: pr::fix
