Repository wkentaro/labelme, pull requests merged in 2025-03, with the labels that each got.

#1548 Relax requirements version
  pyproject.toml
  uv.lock
Labels: pr::other

#1549 Fix missing stderr in gdown download in osam
  labelme/__main__.py
  labelme/widgets/canvas.py
Labels: pr::fix

#1552 Rename labelme.ai -> labelme._automation
  labelme/_automation/__init__.py
  labelme/_automation/bbox_from_text.py
  labelme/_automation/polygon_from_mask.py
  labelme/ai/__init__.py
  labelme/app.py
  labelme/widgets/canvas.py
Labels: pr::other

#1556 Handle when response.annotations[0].bounding_box is None in ai_mask mode
  labelme/widgets/canvas.py
Labels: pr::fix

#1557 Introcuce SAM2
  labelme/app.py
  labelme/config/default_config.yaml
  pyproject.toml
  uv.lock
Labels: pr::feature

#1558 Fix Canvas.finalise with SAM
  labelme/widgets/canvas.py
  pyproject.toml
Labels: pr::fix

#1559 Add type annotations for ai_prompt_widget.py
  labelme/widgets/ai_prompt_widget.py
  pyproject.toml
Labels: pr::other

#1560 Support shape type "mask" in conversion (labelme_draw_json, labelme2voc.py, labelme_export_json, labelme_json_to_dataset)
  .github/workflows/ci.yml
  examples/primitives/primitives.json
  labelme/cli/export_json.py
  labelme/cli/json_to_dataset.py
  labelme/utils/shape.py
Labels: pr::feature

#1534 Add available Linux package managers to README.md
  README.md
Labels: pr::other

#1561 Remove labelme_json_to_dataset command
  .github/workflows/ci.yml
  examples/tutorial/README.md
  examples/tutorial/apc2016_obj3/img.png
  examples/tutorial/apc2016_obj3/label.png
  examples/tutorial/apc2016_obj3/label_names.txt
  examples/tutorial/apc2016_obj3/label_viz.png
  examples/tutorial/apc2016_obj3_json/img.png
  examples/tutorial/apc2016_obj3_json/label.png
  examples/tutorial/apc2016_obj3_json/label_viz.png
  examples/tutorial/load_label_png.py
  labelme/cli/json_to_dataset.py
  pyproject.toml
Labels: pr::other

#1566 Fix missing check for self._sam in Canvas.finalise
  labelme/widgets/canvas.py
Labels: pr::fix

#1570 Remove unused ColorDialog
  labelme/widgets/__init__.py
  labelme/widgets/color_dialog.py
Labels: pr::other

#1572 Mypy
  labelme/__main__.py
  labelme/app.py
  labelme/cli/draw_json.py
  labelme/cli/export_json.py
  labelme/cli/on_docker.py
  labelme/shape.py
  labelme/utils/shape.py
  labelme/widgets/ai_prompt_widget.py
  labelme/widgets/brightness_contrast_dialog.py
  labelme/widgets/canvas.py
  labelme/widgets/escapable_qlist_widget.py
  labelme/widgets/file_dialog_preview.py
  labelme/widgets/label_dialog.py
  labelme/widgets/label_list_widget.py
  labelme/widgets/tool_bar.py
  labelme/widgets/unique_label_qlist_widget.py
  labelme/widgets/zoom_widget.py
  pyproject.toml
  uv.lock
Labels: pr::other
