Repository wkentaro/labelme, pull requests merged in 2025-08, with the labels that each got.

#1623 docs: link to new install-labelme-terminal doc (using uv)
  README.md
Labels: pr::docs

#1613 Fix closure issue in brightness/contrast slider label update
  labelme/widgets/brightness_contrast_dialog.py
Labels: pr::fix

#1624 feat: validate shape JSON objects in LabelFile
  labelme/__init__.py
  labelme/_label_file.py
  labelme/app.py
  labelme/cli/draw_json.py
  labelme/cli/export_json.py
Labels: pr::feature
